<html>
<head>
<title></title>
<script type="text/javascript">
flag=1
function f1()
{
    alert("HAYS CRUSH MO KO HANO")
}
function f()
{
    if(flag==1)
        {
            Bn.style.top=364
            Bn.style.left=300
            flag=2
        }
    else if(flag==2)
        {
            Bn.style.top=476
            Bn.style.left=78
            flag=3
        }
    else if(flag==3)
        {
            Bn.style.top=358
            Bn.style.left=147
            flag=4
        }
    else if(flag==4)
        {
            Bn.style.top=490
            Bn.style.left=134
            flag=5
        }
    else if(flag==5)
        {
            Bn.style.top=234
            Bn.style.left=150
            flag=6
        
        }
    else if(flag==6)
        {
            Bn.style.top=441
            Bn.style.left=245
            flag=7
        }
    else if(flag==7)
        {
            Bn.style.top=345
            Bn.style.left=158
            flag=8
        }
    else if(flag==8)
        {
            Bn.style.top=390
            Bn.style.left=165
            flag=9
        }
    else if(flag==9)
        {
            Bn.style.top=231
            Bn.style.left=349
            flag=10
        }
    else if(flag==10)
        {
            Bn.style.top=123
            Bn.style.left=289
            flag=11
        }
    else if(flag==11)
        {
            Bn.style.top=259
            Bn.style.left=109
            flag=12
        }
    else if(flag==12)
        {
            Bn.style.top=300
            Bn.style.left=170
            flag=13
        }
    else if(flag==13)
        {
            Bn.style.top=267
            Bn.style.left=120
            flag=14
        
        }
    else if(flag==14)
        {
            Bn.style.top=126
            Bn.style.left=170
            flag=15
        }
    else if(flag==15)
        {
            Bn.style.top=298
            Bn.style.left=347
            flag=16
        }
    else if(flag==16)
        {
            Bn.style.top=345
            Bn.style.left=165
            flag=2
        }    
}
</script>

</head>
<body>
<center>
<h1> DATE TAYO SA SUNDAY??? </h1>
<img src="https://c.tenor.com/CFgV1LBRHs0AAAAC/please-cat.gif" height="200" />
<h1 style="#"></h1>
<div id="By" style="position:absolute; left:30%; top:370px; width:210px;
height:210px;">
<input type="button" value=" YES OFC" onClick="f1()" />
</div>
<div ID="Bn" style="position:absolute; left:55%; top:370px; width:210px; height:210px;">
<input type="button" value=" NO " onMouseOver="f()" />
</div>
</center>
</body>
</html>
